# global:
#   scrape_interval: 15s
#   evaluation_interval: 15s

# scrape_configs:
#   - job_name: 'api'
#     static_configs:
#       - targets: ['api:8001']
#     metrics_path: '/metrics'
  
#   - job_name: 'mlflow'
#     static_configs:
#       - targets: ['mlflow:5000']
#     metrics_path: '/metrics'

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Local API endpoint - use host.docker.internal for Docker Desktop
  - job_name: 'api'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics'
  
  # MLflow metrics
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    metrics_path: '/metrics'